### ISSUE TITLE
Parameters for application execution

### ISSUE THREAD

**Issue by unatis** [2gis/Winium#17]
Hi there! I have a question about application execution with parameters. In your example with calculator we see C# code:
DesiredCapabilities dc = new DesiredCapabilities();
dc.SetCapability("app", @"C:/windows/system32/calc.exe");
Tell me please how can I launch application with parameters for example:
dc.SetCapability("app", @"C:/windows/system32/notepad.exe c:/text.txt");
In my case it is :
dc.SetCapability("app", @"C:/windows/system32/msiexec.exe /i c:\installer.msi");

When I try to do this I get exception
{"Path \"C:/windows/system32/notepad.exe c:/ObserveITWebServices_SetupAction.txt\" doesn't exists"}

Thanks in advance!

**Comment by NickAb** [comment]
There is `args ` capability which is for some reason is not yet documented.

```cs
dc.SetCapability("app", @"C:/windows/system32/notepad.exe");
dc.SetCapability("args", @"c:/text.txt");
```

https://github.com/2gis/Winium/issues/5#issuecomment-149785904

**Comment by NickAb** [comment]
@unatis were you able to solve your issue using `args` capability?

**Comment by unatis** [comment]
Works. Thank you very much!

**Comment by GitHubTestUser5** [comment]
@unatis, could you share the code on how you run the installer?
dc.SetCapability("app", @"C:/windows/system32/msiexec.exe /i c:\installer.msi");

**Comment by NickAb** [comment]
@GitHubTestUser5, please try the following, it should work
```
dc.SetCapability("app", @"C:\windows\system32\msiexec.exe");
dc.SetCapability("args", @"/i C:\installer.msi");
```

**Comment by GitHubTestUser5** [comment]
@NickAb, thanks, that works.
By the way, I have tried the following and that also works.
dc.SetCapability("app", @"C:\installer.msi");
