### ISSUE TITLE
Comparison with earlier alternatives?

### ISSUE THREAD

**Issue by daluu** [2gis/Winium#2]
Not an issue, but just wanted to note that there were earlier projects for Windows Phone automation support but less comprehensive in support of the Windows ecosystem than this project.

Just wondering how those projects compare to this, from the perspective of a novice user who hasn't done much research.

https://winphonewebdriver.codeplex.com
https://github.com/forcedotcom/windowsphonedriver

**Comment by NickAb** [comment]
First of all, lets define three types of "apps" that can be tested on mobile devices:
1. *Web applications*. Web apps are HTML/JS applications that run in browser. In desktop-world one would use ChromeDriver, SafariDriver, etc. to automate such apps.
2. *Native applications*. Native apps are apps that are specifically written for mobile platform, for Windows Phone it usually Silverlight or StoreApps application written in C#.
3. *Hybrid applications*. Hybrid apps are native application that do include an embedded web browser (WebViews) somewhere in interface.

Name|Web|Native|Hybrid|Last update
--------|------|--------|---------|----------------
[winphonewebdriver](https://winphonewebdriver.codeplex.com)|Yes|No|No|Jun 15, 2014
[windowsphonedriver](https://github.com/forcedotcom/windowsphonedriver)|Yes|No|No|Sep 29, 2014
[Winium.StoreApps](https://github.com/2gis/Winium.StoreApps)|Yes|Not yet implemented|Not yet implemented|Jun 19, 2015
[Winium.StoreApps.CodedUi](https://github.com/2gis/Winium.StoreApps.CodedUi)|Yes|Yes*|Yes*|Jun 24, 2015

So if you are going to automate testing of web apps, then you can choose between [winphonewebdriver](https://winphonewebdriver.codeplex.com), [windowsphonedriver](https://github.com/forcedotcom/windowsphonedriver) and [Winium.StoreApps.CodedUi](https://github.com/2gis/Winium.StoreApps.CodedUi), but I would recommend to try former two first, as CodedUi is an early prototype and based on CodedUi, and not on injecting Selenium Atoms into WebView. FYI, we are planning to add Hybrid and Web apps support to [Winium.StoreApps](https://github.com/2gis/Winium.StoreApps), it is somewhere in roadmap, but there are no definitive timeline.

If you are going to automate testing of native apps, then you have a choice between [Winium.StoreApps](https://github.com/2gis/Winium.StoreApps) and [Winium.StoreApps.CodedUi](https://github.com/2gis/Winium.StoreApps.CodedUi). The former has more features but is limited to testing only on emulators (at the moment) and requires one to embed test-server into app under test. The latter (CodedUi) does not require embedding test-server, supports emulators and devices, but rehires Visual Studio Premium or higher.
