### ISSUE TITLE
Unable to interact with menu items 

### ISSUE THREAD

**Issue by sanjeets** [2gis/Winium#4]
I keep on getting exceptions when I try to interact with menu items for a windows application.
![menubar](https://cloud.githubusercontent.com/assets/4698614/10499527/12c3f222-728e-11e5-97ef-8d77b698d269.png)

**Comment by skyline-gleb** [comment]
Hi,
you have tried to repeat with start driver as administrator? For https://github.com/2gis/Winium.Desktop/issues/55 it basic idea for solving.

**Comment by sanjeets** [comment]
I got it working :)

**Comment by skyline-gleb** [comment]
cool.
