### ISSUE TITLE
Illegal chars in execution line

### ISSUE THREAD

**Issue by sanjeets** [2gis/Winium#5]
I am trying to launch the following application which has command line params.
Can this be done
I am using python.
For example
applocation = '"C:\Program Files\Compuware\Uniface 9.2.01\bin\uniface.exe" /ini=\inis\PMMQA2.AJB.INI'
Then When I try to do the following:
self.driver = Remote(command_executor="http://localhost:9999",
                             desired_capabilities=self.desired_capabilities)
I get the following error message:
u'Illegal characters in path.'

What could be the reason for this?

**Comment by skyline-gleb** [comment]
Hi,
use `args` capability:
```python
driver = webdriver.Remote(
    command_executor='http://localhost:9999',
    desired_capabilities={
        'app': 'C:\Program Files\Compuware\Uniface 9.2.01\bin\uniface.exe',
        'args': '/ini=\inis\PMMQA2.AJB.INI'
    })
```

**Comment by sanjeets** [comment]
Thank you will give that a try.
BTW you have been awesome at responding.
THANKS :)
