### ISSUE TITLE
Any plans to implement getLocation

### ISSUE THREAD

**Issue by sanjeets** [2gis/Winium#6]
I am getting the following error when trying to get a location of an element.
 signonWin.location
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 364, in location
    old_loc = self._execute(Command.GET_ELEMENT_LOCATION)['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 454, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: 'getElementLocation' is not valid or implemented command.

**Comment by skyline-gleb** [comment]
Its real. But why would you want to use? We have not encountered such a need, it's interesting.

**Comment by sanjeets** [comment]
There are situations where I am unable to click on an element so need to find its location and use another module to click on it.

**Comment by skyline-gleb** [comment]
Why you unable to click? Maybe i can help. I know 3 options for clicks.

**Comment by sanjeets** [comment]
Yes

**Comment by tkurnosova** [comment]
What ControlType of this element? The element is visible?

**Comment by sanjeets** [comment]
Its a windows pane, yes its visible

**Comment by tkurnosova** [comment]
Could you give code example?

**Comment by NickAb** [comment]
Closing this issue in favour of same issue was filed at Winium.Desktop repo https://github.com/2gis/Winium.Desktop/issues/95

@sanjeets please see referred issue for current workaround to get element location.

**Comment by aman019** [comment]
Hi, i am also facing similar issue. What i am trying to achieve to get the screenshot of a particular web element rather than the entire screen. I am getting following error. Any help would be highly appreciated. 

org.openqa.selenium.UnsupportedCommandException: 'getElementLocation' is not valid or implemented command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2 milliseconds
