### ISSUE TITLE
How to focus new popup window

### ISSUE THREAD

**Issue by yarafath8** [2gis/Winium#67]
Hey, 
I'm using Winium with Java for my WPF project.
My app goes like this, 
Launch -> Username/Password is requested.
After successful authentication -> A window will popup for some selection.

My script does not focus the element present in the new winfow.
How do I focus to the next new window ? Please suggest

**Comment by bharadwaj-pendyala** [comment]
Did you try getWindowHandle method?

**Comment by yarafath8** [comment]
@bharadwajpenydala, Yes I tried using getWindowHandles(). Did not work out for me.

**Comment by ankitvaish04** [comment]
Try this:
1) Get the parent window handle before performing the last action on parent window:
String parent = driver.getWindowHandle().toString();
System.out.println("Parent window handle: " + parent);

2) Perform last action on the parent window, and wait for child window to open for example:
driver.findElementByName("New Email").click();
Thread.sleep(5000);

3) Then get the window handle of child window:
String child = driver.getWindowHandle().toString();
System.out.println("Child window handle: " + child);

4) Then use the following line to switch back to the parent window:
driver.switchTo().window(parent);

and then again to child window if required:
driver.switchTo().window(child);
