### ISSUE TITLE
To Press the Keyboard keys using Winium in C#

### ISSUE THREAD

**Issue by ghost** [2gis/Winium#92]
I want to press the Keyboard keys using Winium in C#

Could anyone tell me how to press the keyboard keys   using** Winium in C#** 

No Java codes please as I am not a programmer....

**The Code (Winium C#) to Open a Desktop application and logging using a password is as below:**

private void button2_Click(object sender, EventArgs e)     // Button Click event in Windows Form 
        {
            DesktopOptions options = new DesktopOptions();
            options.ApplicationPath = @"C:\XXXX\xx.exe";      // XXXX just represents the exe file location
            WiniumDriver driver = new WiniumDriver(@"C:\Users\Winium.Desktop.Driver", options);

            driver.FindElementById("txtPassword").SendKeys("XXXXX"); // Enters Password
            driver.FindElementById("cmdOK").Click();   // Clicks the Login Button
           

            // After logging into the application I want to press the F1 using the example codes as below

            driver.Keyboard.PressKey("%o");     // To press Alt and o but it doesn't work

           SendKeys.Send("{F1}");                    // To Press F1 Key but it doesn't work
         
            driver.Keyboard.SendKeys("{F2}"); // To Press F2 Key but it doesn't work
        }

 
Kindly help me in this regard.
Thanks
Naren

**Comment by truptibhatt** [comment]
You can try Action Class:
 WebElement ele= driver.findElement(locator1);
Actions action= new Actions(driver);
action.sendKeys(ele,Keys.F2).build().perform();

**Comment by ghost** [comment]
Hi Truptibhatt
Thank you for your comment
When I tried to use
Actions action= new Actions(driver);
I am getting an error in the driver mentioned in the Actions?

I dont know how to use the Action Class.. Could you tell me how to define it?

Moreover I dont want to find any element to press that F2 key. Its a shorcut key in the application which I had opened using winium..

I just want to pass the keys F2 after opening the application.

Thanks
Naren

**Comment by ghost** [comment]
> You can try Action Class:
> WebElement ele= driver.findElement(locator1);
> Actions action= new Actions(driver);
> action.sendKeys(ele,Keys.F2).build().perform();

Hi Truptibhatt
Thank you for your comment
When I tried to use
Actions action= new Actions(driver);
I am getting an error in the driver mentioned in the Actions?

I dont know how to use the Action Class.. Could you tell me how to define it?

Moreover I dont want to find any element to press that F2 key. Its a shorcut key in the application which I had opened using winium..

I just want to pass the keys F2 after opening the application.

Thanks
Naren
